# Generated by Django 6.0.5 on 2026-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='ACITP', max_length=120)),
                ('hero_badge', models.CharField(default='ONG ACITP - A CASA DO IDOSO PARA TODOS OS POVOS', max_length=180)),
                ('hero_title', models.CharField(default='Cuidando de quem sempre cuidou de nos', max_length=180)),
                ('hero_description', models.TextField(default='Ha 15 anos levando dignidade, amor e qualidade de vida para idosos em situacao de vulnerabilidade.')),
                ('history_title', models.CharField(default='Uma decada de amor e dedicacao', max_length=180)),
                ('history_description', models.TextField(default='Fundada em 2010, a ACITP nasceu para acolher idosos em vulnerabilidade com dignidade, cuidado e presenca diaria.')),
                ('history_highlight', models.CharField(default='Nossa Historia', max_length=140)),
                ('director_role', models.CharField(default='Diretor e Fundador', max_length=120)),
                ('director_name', models.CharField(default='Pastor Marcio Vieira', max_length=120)),
                ('services_title', models.CharField(default='Nossos Servicos', max_length=140)),
                ('services_description', models.TextField(default='Oferecemos um cuidado integral, atendendo as necessidades fisicas, emocionais e sociais dos nossos idosos.')),
                ('donation_title', models.CharField(default='Apoie Nossa Causa', max_length=140)),
                ('donation_description', models.TextField(default='Sua contribuicao ajuda na alimentacao, nos medicamentos, nos eventos e na manutencao da instituicao.')),
                ('pix_key', models.CharField(default='acitp2010@gmail.com', max_length=180)),
                ('volunteer_title', models.CharField(default='Seja Voluntario', max_length=140)),
                ('volunteer_intro', models.TextField(default='Doe seu tempo e suas habilidades. Precisamos de pessoas dispostas a fazer companhia, apoiar e cuidar.')),
                ('volunteer_benefits', models.TextField(default='Atividades recreativas e culturais\nAcompanhamento em consultas medicas\nApoio administrativo e logistico\nOficinas de artesanato e musica')),
                ('contact_phone', models.CharField(default='(+55) 21 96441-4945', max_length=40)),
                ('contact_email', models.EmailField(default='acitp2010@gmail.com', max_length=254)),
                ('contact_address', models.TextField(default='Estrada do Babi, 14455, Vila Magalhaes em Belford Roxo')),
                ('footer_text', models.TextField(default='Transformando vidas com amor e dignidade desde 2010. Cada idoso merece ser cuidado com carinho.')),
                ('hero_image', models.FileField(blank=True, null=True, upload_to='site/')),
                ('events_banner', models.FileField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Configuracao do site',
                'verbose_name_plural': 'Configuracao do site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('is_featured', models.BooleanField(default=True, verbose_name='Destacar na home')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
    ]
